### ISSUE TITLE
Async hooks

### ISSUE THREAD

**Issue by louy** [SierraSoftworks/Iridium#19]
I believe [hooks](https://github.com/SierraSoftworks/Iridium/blob/release/lib/Hooks.ts) should be able to return promises. Otherwise they become useless sometimes.

**Comment by SPARTAN563** [comment]
Hi @louy,

As mentioned in my response to #21 - this was a design decision made to help prevent users from accidentally hurting the performance of their applications - keeping in mind that hooks run for every query you make. By removing the ability to run blocking async operations in hooks, the idea was that developers would be forced to think about when they perform those operations and instead only do them when necessary.

Something else to keep in mind is that promises **have to** be dispatched asynchronously, even if they could be resolved synchronously, as failure to do so can result in stack overflow conditions in situations where they would otherwise not occur. This async dispatch incurs a performance overhead and can significantly impair the performance of operations, regardless of whether the user opts to make use of an async hook or not.

If we do decide to add them back in, I think the best idea will be to add explicit async hook entries like `onCreatedAsync` with documentation explaining why using them is a bad idea for performance and what better solutions are available. How does that sound to you?

**Comment by SPARTAN563** [comment]
Just in reply to your comment on #21 - definitely a valid point about other libraries offering the functionality though there are obviously differences across the different architectures which change what can and can't be done from a performance perspective. For example, node-orm2 (at least when I last spent time contributing to the codebase) was entirely callback driven - which doesn't have quite as much overhead as promises, but obviously can run into stack overflow issues and is more effort to make use of from a dev perspective. One of the optimizations you can do in that case is to inspect the hook's `function.length` to determine whether there is a callback argument, and operate in synchronous mode if it is not present.

Unfortunately in the promise case, it is necessary to actually execute the function to discover whether it is a promise or not - at which point it is faster to just execute the function and let the promise library handle everything else for you.

I see your point about implementing specific methods though, and do agree that it really isn't the ideal solution - after all, if you're implementing your own DAL/BLL there really isn't much of a need for an ORM/ODM in the first place. With that in mind, let me look at implementing a test version of the `on___Async` hook package and let's see how that pans out - won't have the chance to do so now as I've got a couple of meetings coming up but will take a look later this evening or tomorrow morning.

**Comment by louy** [comment]
Honestly I doubt that this has any performance impact when not using async hooks —besides calling `process.nextTick()`, which isn't a bad thing really. The original calls are [already wrapped](https://github.com/SierraSoftworks/Iridium/blob/release/lib/ModelHandlers.ts#L69-L70) in a promise to avoid throws I guess.

As for callbacks, yeah they might be a bit faster but are really a disaster. Esp. with thrown runtime errors.

As for implementing on__Async hooks, I honestly think this is an over-complication. It would do but you'll end up with two hooks for everything. And it wouldn't stop anyone from using them. Just adding a warning to regular hooks would do the same in my opinion.

Your point about developers mistakenly affecting performance is valid, but the simplicity you get in return is worth it. This is why we're using Javascript instead of some low-level language after all. Simplicity.

Lastly, if you're really concerned about performance while not using async hooks I think we can create a perf-test and compare results. What do you say?

**Comment by SPARTAN563** [comment]
Luckily for us, there's already a benchmark test there which tests out just this sort of stuff :wink:. Reason I'm actually mentioning it is that it was removed as part of a performance boosting refactor about 4 months ago, so not completely unfounded or hypothetical. Keep in mind that each `.then()` results in using `process.nextTick()`, which while faster than `setTimeout(0)` is still a LOT slower than the sync method call as it needs to go via the event queue. You'll notice that while there is still extensive use of promises throughout the pipeline, the number of promises generated has been kept to a minimum in order to reduce the effect this has on performance (especially when inserting/querying large numbers of documents).

Totally agree with the callback issue :smile: - wouldn't be too bad if libraries implemented the correctly, but that's a vain hope.

Also true, however you'd be bringing awareness to the fact that you are making use of that - and opting into the performance impact rather than having it forced on you. There are many other use cases for hooks which don't require async operations - such as setting default values or performing simple transformations.

Will look into it some more and keep discussing to see if there's a good middle ground.
