### ISSUE TITLE
Iridium Model Helpers not included

### ISSUE THREAD

**Issue by peek4y** [SierraSoftworks/Iridium#24]
index.js - ModelHelpers is not included.

**Comment by SPARTAN563** [comment]
Hi @peek4y - just want to clarify what exactly you mean, I assume you are referring to the fact that the [`ModelHelpers`](http://sierrasoftworks.github.io/Iridium/classes/modelhelpers.html) aren't exported from `index.js`?

If that is the case, then it is intentional - the [`ModelHelpers`](http://sierrasoftworks.github.io/Iridium/classes/modelhelpers.html) and [`ModelHandlers`](http://sierrasoftworks.github.io/Iridium/classes/modelhandlers.html) classes are both intended for internal use. If you need to access them for whatever reason, you can do so on the model itself through the [`handlers`](http://sierrasoftworks.github.io/Iridium/classes/model.html#handlers) and [`helpers`](http://sierrasoftworks.github.io/Iridium/classes/model.html#helpers) properties.

**Comment by peek4y** [comment]
Ah, got it. Thanks.
