### ISSUE TITLE
Format of Modified different from Original

### ISSUE THREAD

**Issue by peek4y** [SierraSoftworks/Iridium#25]
``` javascript
_original:
 { _id: 5672568cf23db0741194b0a5,
   email: 'tes@est.com',
   username: 'test',
   users: [ [Object] ] },
_modified:
 { _id: { _bsontype: 'ObjectID', id: 'VrV?ò=°t\u0011?°¥' },
   email: 'tes@est.com',
   username: 'test',
   users: [ [Object] ] }
``` 

Why don't I get the '5672568cf23db0741194b0a5' as a MongoDB.ObjectID type in _modified, this effects "toJSON()" as well, I don't get the ObjectID as type ObjectID ("5672568cf23db0741194b0a5")

**Comment by SPARTAN563** [comment]
Will be fixed in a second, it's got to do with the way [`lodash`](https://lodash.com/) clones certain types of objects - have to manually add exceptions for them to make sure they aren't cloned in their broken form.

It affects `MongoDB.ObjectID`, `MongoDB.Binary` and `Buffer` to my knowledge, but if you bump into any others please let me know.

**Comment by peek4y** [comment]
Oh! 

Thanks for fixing! Nothing else so far.

So this fix is going along with the $document related changes for https://github.com/SierraSoftworks/Skmatc/issues/1 ?

**Comment by SPARTAN563** [comment]
That's right, it'll all be released as part of the same bundle - soon as I get `npm publish` to work on my home machine - doesn't seem particularly happy for some reason.
