### ISSUE TITLE
How to declarate default value?

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [SierraSoftworks/Iridium#36]
![image](https://cloud.githubusercontent.com/assets/19378179/15452453/48c1b0dc-1ff7-11e6-86e4-72df9cd6d6c0.png)

```javascript
list.insert({name:'ololo', age: 11})
// error, friends must be array
```

**Comment by SPARTAN563** [comment]
Hi Ivan,

The most reliable way to do so is by hooking the [onCreating](http://sierrasoftworks.github.io/Iridium/classes/instance.html#oncreating) callback and setting it up there.

```typescript
class User extends Item<UserDocument, User> implements UserDocument {
  @Property(true)
  name:string

  @Property([String])
  friends:string[]

  @Property(true)
  age:number

  static onCreating(doc: UserDocument) {
    doc.friends = doc.friends || []
  }
}
```

You can also use the standard ES6 initializer, however I haven't tested it myself as much, so please let me know if you bump into any issues with it (I suspect you will when running `insert`/`create` as it will only create an instance after inserting the document, I may need to look at improving that at some point).

```typescript
class User extends Item<UserDocument, User> implements UserDocument {
  @Property(true)
  name:string

  @Property([String])
  friends:string[] = []

  @Property(true)
  age:number
```

**Comment by uMaxmaxmaximus** [comment]
why onCreating? why not in constructor?

**Comment by SPARTAN563** [comment]
So currently that's because the constructor is only called **after** a document has been received from the database. In the case of `insert` or `create` being called, this means that validation and insertion is performed before calling the instance's constructor, so you'd be validating and inserting something before it had the chance to set the default.

As for why it's not on the `@Property` decorator, skmatc (the tool used to do validations) is designed purely for validation and with the guarantee that it doesn't modify your data. By allowing it to set a default value (which is what you're looking for) you would become significantly more difficult to reason about the state of the application and to reproduce any errors someone may encounter.

On the other hand, you could also make use of a transform (and even throw together a decorator to help matters there).

```typescript
class User extends Item<UserDocument, User> implements UserDocument {
  @Property(true)
  name:string

  @Property([String])
  @Transform(value => value || [], value => value || [])
  friends:string[];

  @Property(true)
  age:number
}
```

If you wanted a decorator to do this for you, you'd just need to add this:

```typescript
import {clone, cloneDeep} from "lodash";

export function Default(value: any) {
  return function(target: Iridium.Instance<any, any>, property: string = "$document"): void {
    let staticTarget = <Iridium.InstanceImplementation<any, any>>target.constructor;
    staticTarget.transforms = clone(staticTarget.transforms || {});
    staticTarget.transforms[property]  = {
      fromDB: x => x || cloneDeep(value),
      toDB: x => x || cloneDeep(value)
    };
  }
}
```

:warning: **warning** This decorator will overwrite any other transforms you have on a property, so you'd probably want to add some logic for merging them (check whether `staticTarget.transforms[property]` already exists and, if so, call its methods after you have determined the default value).

That then allows you to use it like this:

```typescript
class User extends Item<UserDocument, User> implements UserDocument {
  @Property(true)
  name:string

  @Property([String])
  @Default([])
  friends:string[];

  @Property(true)
  age:number
}
```

**Comment by uMaxmaxmaximus** [comment]
It is strange that such a necessary part is not part of the core.

**Comment by SPARTAN563** [comment]
Perhaps, I simply haven't run into a situation where the `onCreated()` hook was significantly more effort to create and manage than decorators for defaults. Not only that, but the decorator approach eschews type safety on its values - potentially breaking things in difficult to find ways, while the `onCreated` hook approach allows the TypeScript compiler to verify that you're assigning the correct type.

Something I would like to look at possibly adding is triggering the constructor **before** validation, allowing you to use constructor (or ES6) default assignments instead. The issue is that it may create a performance issue when inserting a large number of documents, something which I'd like to avoid. It may also require changes to the API - which is something I also am trying to prevent, since it causes numerous headaches for people using the library.

**Comment by uMaxmaxmaximus** [comment]
But I thought concept of the declaration the properties is this:

```typescript
class User extends Instance {
    
    @Property({index: true, default: 'Ololo', optional: true})
    name:string

    @Property({default:0, min: 0, max: 200, int:true})
    age:number
}
```

No?

**Comment by SPARTAN563** [comment]
Currently no, the arguments it accepts are of this format:

```typescript
Property(asType: any, required?: boolean)
Property(name: string, asType: any, required?: boolean)
```

The two overloads are intended to be used on the property and class level respectively, so like this:

```typescript
@Property('age', Number)
class User extends Instance {
  @Property(String)
  name: string

  age: number
}
```

In addition to that, the `required` argument allows you to quickly write an optional property without specifying the full skmatc for it - so `@Property(String, false)` is an optional string property, but it really rewrites it into `@Property({ $type: String, $required: false })`.

Skmatc's syntax offers the following:

 - Base types (`Number`, `String`, `Boolean` etc) are checked using `typeof`.
 - Objects are validated recursively, unless all of their properties begin with `$` - in which case they are treated as a rules entry.
 - The ability to validate anonymous properties using `{ $propertyType: String }`, the same as `{ [name: string|int]: string; }`
 - Support for regular expression validation of strings
 - The ability to specify a custom validation message using `$message`.
 - The ability to create custom validators (which we use for ObjectID for example).

You can read a bit more about it [here](https://github.com/SierraSoftworks/Skmatc).

**Comment by uMaxmaxmaximus** [comment]
How can I get the model scheme? is private prop. I need to discover how to get scheme of the model, i want send this information to user by ajax (that he automatically convert data fields to Data object)

**Comment by SPARTAN563** [comment]
You would need to access it from the model itself, so something like this:

```typescript
let user = await this.users.get();
let schema = this.users.schema;

return {
  data: user,
  schema: schema
};
```

**Comment by ArpanRawat** [comment]
Hey any updated on this I am on alpha-14
