### ISSUE TITLE
 MongoError: multi update only works with $ operators

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [SierraSoftworks/Iridium#37]
https://monosnap.com/file/9eEpP3TVlQDSiOo4IHtGspjg1hD7L7.png
![image](https://cloud.githubusercontent.com/assets/19378179/15478040/a6c9ad22-2120-11e6-8974-af7140a918bf.png)

User send json data, i want save it. how to update model?

i have error:  MongoError: multi update only works with $ operators

P.S. this.list is instanceof Model

**Comment by SPARTAN563** [comment]
I see, currently I haven't implemented this because of the potential risks involved in letting anybody directly control what goes into your database - generally I will rather put in place an API which allows you to perform atomic updates and then using something like `_.pick` to select which fields get updated.

That being said, if you wish to directly allow users to modify an item, you can access the underlying collection API directly using `this.list.collection.update({ _id: _id }, data)` - keeping in mind that it doesn't return a promise...

```typescript
saveRaw(data) {
  let _id = toObjectID(data._id);
  return new Bluebird<void>((resolve, reject) => {
    this.list.collection.update({ _id }, data, (err) => {
      if(err) return reject(err);
      return resolve();
    });
  });
}
```

**Comment by uMaxmaxmaximus** [comment]
i filter data object in previos state =)

**Comment by SPARTAN563** [comment]
That's certainly one approach which could be adopted, however is there a reason why you wouldn't want to build that as its own library and then use something like `Object.assign` or `_.assign` to apply the properties?

```typescript
let instance = await model.get(data._id)
Object.assign(instance, { name: data.name, email: data.email })
await instance.save()
```

You can also get the an object containing the properties by using `_.pick` like this:

```typescript
let instance = await model.get(data._id)
Object.assign(instance, _.pick(data, 'name', 'email'))
await instance.save()
```

Or if you have your own library providing the rule functionality, you could do the following:

```typescript
let instance = await model.get(data._id)
myLib.assign(instance, 'name?', 'friends.*.name')
await instance.save()
```

My primary motivation for why I'd suggest creating a separate library is that it doesn't require a new Iridium release whenever we want to fix a bug there, it allows people who aren't using Iridium to access the library's functionality, and it also keeps Iridium's codebase nice and specific (a lightweight MongoDB ORM).

**Comment by uMaxmaxmaximus** [comment]
We need to provide basic things out of the box, but nothing prevents people from using additional plug-ins, if the basic functionality it's not enough. Is not it so?

**Comment by SPARTAN563** [comment]
I think it's a bit beyond the scope of what Iridium is trying to provide - no doubt a useful feature for certain applications and probably not a huge amount of additional code (even with the rule sets) but every little bit extra makes it a bigger and more cumbersome library.

Another thing to keep in mind is that, by adding a default method like `set()` to the `Instance` type, you are adding the potential to break applications which already use a `set()` method on their instance implementations. I've tried to keep the `Instance` API as simple and clean as possible (and will likely be looking to deprecate two of the existing helpers there in the near future) so that there is more space for developers to put down what they're looking for.

On another note, it just crossed my mind that this is the perfect application for a custom Instance type - a large motivation behind why Iridium was designed the way it is.

```typescript
export class PowerInstance<TDoc, TInstance> extends Instance<TDoc, TInstance> {
  set(data:Object, ...props:string[]): TInstance {
        props.forEach(prop => {
            let value = data[prop];
            if (prop in data) this[prop] = value;
        });

      return this
    }
}

class User extends PowerInstance<UserDocument, User> {
  @Property(String)
  name: string;

  @Property(Date)
  birthdate: Date;

  @Property([String])
  friends: string[];
}
```

You then simply derive all your types from `PowerInstance` instead of the standard `Iridium.Instance` and you'll have the `set()` method available for you. You could even provide this as an external module for others to use if you wished?

**Comment by uMaxmaxmaximus** [comment]
By the way, exactly. I did so, I expanded Instance new class and inherit from him. Somehow, I thought that this is a hack, but now realize that this is how it should work)

Thank you so much
