### ISSUE TITLE
ES6 analog

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [SierraSoftworks/Iridium#38]
this is ES6

```javascript
@Index({name: 1})
@Collection('sectors')

class Sector extends Item {

	@Property(true)
	name

	@Property(true)
	texture

}
```

instance getters `name` and `texture` not created

@Property decorator not works???

**Comment by SPARTAN563** [comment]
It should work (I use it extensively myself), but maybe it requires that you specify a default value for the properties (depends on the runtime and your transpiler).

```
@Index({name: 1})
@Collection('sectors')

class Sector extends Item {

    @Property(true)
    name = null

    @Property(true)
    texture = null

}
```

**Comment by h3x3d** [comment]
Babel note:

As i can see, the problem is that babel-plugin-transform-class-properties actually places property initialization to constructor, so, getters/setters, generated on proxy class in ModelSpecificInstance are overrode when actual instance is created.

So, the only option i can see is to set schema directly, like so:

````javascript
@Collection('test')
class Test extends Instance {
  static schema = {
    _id: false,
    name: String
  }
}
````
