### ISSUE TITLE
Look at my ORM please =)

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [SierraSoftworks/Iridium#45]
npm https://www.npmjs.com/package/ormjs

this is code https://github.com/uMaxmaxmaximus/ui-js/tree/master/server/lib/orm
I think this is epic =) It is very very very very very elegant API. What do you think about it?

1) Actually, ArangoDB a graph-oriented database, so that in the future, I will describe these relationships using the edges of the graph, for optimization.

2) And add drivers platform for another databases, like Mongo e.t.c.

**Comment by uMaxmaxmaximus** [comment]
Actually, ArangoDB a graph-oriented database, so that in the future, I will describe these relationships using the edges of the graph, for optimization.

**Comment by uMaxmaxmaximus** [comment]
please look at this, I need your opinion

**Comment by SPARTAN563** [comment]
Hi Ivan,
I've been away the better part of last week, sorry I'm only getting around to this now.

It looks interesting, while I like the idea of using `async/await` for all graph navigations, I'm apprehensive about the performance penalties of such an approach (particularly on frequently used properties, where someone who doesn't understand those semantics may end up accidentally degrading performance to a significant degree).

I'd also recommend prefixing all schema options (`min`, `max`, `test`, `set` etc) with a `$` symbol, since it makes it explicit that they are options in the schema as opposed to nested properties, something which makes reading the code (and verifying that you're working with an options object) easier.

Finally, as far as graph DBs being "the future", I'm not entirely sure I agree. They are certainly a very powerful tool for certain classes of problem (the friend graph being one of them), however there are reasons you'd chose a document DB or relational DB for different problems, they all offer advantages in specific fields and it's about finding what is the best fit for your problem area rather than what the best DB is.

**Comment by uMaxmaxmaximus** [comment]
How can you not understand the semantics of if you use the operator await? =)
P.S. ArangoDB is a graph of documents actually. like javascript object link to another object,

```javascript
user1 = {}
user2 = {}
user1.friend = user2 //friend is ende of graph
```

graph oriented databases is evolutional document collections databases
in core his create system collection with two fields 

Edges{from:_id, to: _id}

and indexing this

**Comment by SPARTAN563** [comment]
Remember that most people don't have much (if any) experience writing high quality async code. Tools like `async` and `await` further hide the complexities and nature of this code behind "magic" - so there's likely to be a lot of people that see your examples and go "Oh, I guess I just need to add await to make it work." without understanding that there is a network request behind that. Not a huge issue if you don't intend to cater to those people, but worth keeping in mind.

Yeah, graphs are really useful for many classes of problems (and can easily handle relational and document type workloads from a functionality perspective) however it's worth keeping in mind that there's a whole bunch of extra overhead - you'll see ArangoDB referencing their memory usage as a concern, something which may put it out of reach of people on a budget, and may even introduce scaling constraints at significant workload sizes - things which aren't necessarily present in other DB systems.

Another aspect is that, due to the way graphs work, many of your more complex queries require a join (of sorts) and hence it limits your ability to horizontally scale things while maintaining performance.

**Comment by uMaxmaxmaximus** [comment]
> without understanding that there is a network request behind that.

How can you not understand the semantics of if you use the operator await? =)
`await user.friend === await user.friend` // is cached actually

```javascript
await user.friend // only one query to db on this
await user.friend // from cache
await user.friend // from cache
await user.friend // from cache
await user.friend // from cache
```
if we need update we need update friend and sync from db:
```javascript
let friend = await user.friend
await friend.update()
```

**Comment by SPARTAN563** [comment]
I see, in that case it's less of an issue - still worth remembering that it's creating a promise there, so not anywhere near as fast as something like:

```js
let friend = await user.friend
friend.x
friend.x
friend.x
friend.x
```

Another thing to be careful about is how you hold stuff in the cache, you can quickly run out of memory in-process if you're holding strong references to objects (the GC can't collect them). Perhaps investigate using `WeakMap` if it's available on your platform to help avoid that issue.

**Comment by uMaxmaxmaximus** [comment]
Hmm, good idea, I can remember the number of cached objects to PROMIS, and when the amount exceeds the permissible 1000, I will reset the cache, and set getters again

**Comment by SPARTAN563** [comment]
That's an idea, but remember that doing that approach may introduce strange performance issues which will be hard for someone unfamiliar with the ORM to diagnose. A better solution might be a [LRU cache](https://en.wikipedia.org/wiki/Cache_algorithms) which keeps the last 1000 most recently accessed objects and removes everything else?

Alternatively, if you're only caching stuff on a local object (using a promise's resolved value) and not caching stuff like `db.user.get(...)` then you shouldn't have any significant issues unless your graph becomes exceptionally deep.

**Comment by SPARTAN563** [comment]
Another thing worth keeping in mind is that, if you have reference equality for objects in certain situations (`await user.friend === await user.friend`) then people are going to start assuming that it exists across boundaries (`await user1.friend === await user2.friend`) which may or may-not be the case.

**Comment by uMaxmaxmaximus** [comment]
> Alternatively, if you're only caching stuff on a local object (using a promise's resolved value) and not caching stuff like db.user.get(...) then you shouldn't have any significant issues unless your graph becomes exceptionally deep.
About that speech, promises is stored directly in the properties of objects, and when the object is removed and the promises deleted.


> A better solution might be a LRU cache
That's what I mean) I just difficult to formulate his thoughts in a foreign language, and I'm trying to simplify.

By the way I'm from Russia, appreciate my English language on a ten-point scale)

**Comment by SPARTAN563** [comment]
Had picked that up, for a second language speaker it's very good - end of the day, if people understand you then that's good enough (I'm a second language speaker for the language we use at work, I know how tricky it can be).
