### ISSUE TITLE
Use native Promises?

### ISSUE THREAD

**Issue by pyros2097** [SierraSoftworks/Iridium#52]
Is is possible for you to switch to using native promises instead of bluebird since node version 4 has promises inbuilt?
Since this is breaking my typechecking like this?

```
Type 'Bluebird<App>' is not assignable to type 'Promise<App>'.
```

**Comment by SPARTAN563** [comment]
The motivation for choosing Bluebird was primarily a performance one, from what I understand, the native Promise implementations in Node.js still lag behind Bluebird on that front. Since those promises are used extensively within Iridium's implementation, and since performance is one of our primary goals, I've opted to stick with Bluebird until a compelling argument is raised for switching.

More information on the performance differences can be found here:
- http://bluebirdjs.com/docs/benchmarks.html
- https://spion.github.io/posts/analysis-generators-and-other-async-patterns-node.html

As far as fixing the issue you're seeing, are you attempting to return a result from Iridium as a `Promise`? If so, your options would be to typecast it (Bluebird is A+ compatible, so you shouldn't have any issues) or alternatively switch to using Bluebird in your application (which may not be a bad idea at all from a performance perspective).
