### ISSUE TITLE
Not required field in Property

### ISSUE THREAD

**Issue by Granga** [SierraSoftworks/Iridium#53]
I have this interface:
```
interface IBar {
    foo?: boolean;
}
```

and in my model, this property schema:
```
...
@Property({
    bar: Boolean
})
foo: IBar;
...
```

How can I make `foo` to not be required and not get this error message: 
`Expected foo.bar to be a defined non-null value but got undefined instead`

**Comment by SPARTAN563** [comment]
It's relatively straightforward, Skmatc (the validator used by Iridium) allows you to provide control structures instead of types, these have all of their fields prefixed with a `$` and in your case would look like this:

```typescript
@Property({
  bar: { $type: Boolean, $required: false }
})
foo: IBar;
```

Let me know if you run into any issues, you can also use `$message` if you want to provide a custom validation message (useful for things like email addresses etc).

**Comment by Granga** [comment]
@SPARTAN563 It works. Thank you!

**Comment by KrzychuJedi** [comment]
@SPARTAN563 Is it described somewhere in docs?
