### ISSUE TITLE
Update with set

### ISSUE THREAD

**Issue by ChrLipp** [SierraSoftworks/Iridium#58]
A support question: How do I update an element with the set operator? 

Background: I am implementing an CRUD Rest service. In the update case I don't receive all fields, so I am calling update only with a subset of the existing fields. I want to avoid a findOne followed by an update and want to do this in one operation.

Whats the standard way to do this in Iridium?
Thanks for your work!

**Comment by SPARTAN563** [comment]
Hi Christian,

The approach I generally take is to combine this with the [lodash](https://lodash.com/) [`pick`](https://lodash.com/docs/4.17.2#pick) function to prevent abuse of my APIs (while keeping things DRY).

```typescript
import {pick} from "lodash";
```

```typescript
// Example request params
const params = {
  id: "0123456789abcdef01234567"
};

// Example request body
const body = {
  "name": "Benjamin",
  "email": "can't change this",
  "date_of_birth": new Date(0)
};

db.Model.update({ _id: Iridium.toObjectID(params["id"]) }, {
  $set: pick(body, "name", "date_of_birth")
}).then(changed => {
  if (!changed) throw new Error("No user matched the ID provided, or no changes were made");
  return { changed };
});
```

Of course, if you don't have any security concerns (and are feeling like opening yourself up to a world of headaches) you can do away with the `pick` and just pass `req.body` as your `$set` operation context.

**Comment by ChrLipp** [comment]
Thanks for your example, this is exactly what I was looking for. 
I understand now how the update works.

I understand also the necessity to map/pick the request. But I believe the lodash pick approach is only suitable for smaller services. If you have an object tree I think a mapper is easier to work with. So I tested [AutoMapper](https://github.com/loedeman/AutoMapper) and [cerialize](https://github.com/weichx/cerialize).

However this solutions require a ctor without arguments so that the mapper can create the document. This is not possible with Iridium, so I have to use a DTO to map the request first to the DTO and then save it with Iridium. So I have to maintain a duplicate data structure because I cannot reuse the Iridium document.

What's your architectural approach for more complex (read business) applications?

**Comment by SPARTAN563** [comment]
I see cerialize (thanks for the link) does have an option to deserialize into an existing object, so that's the approach I'd take. One thing which may pose an issue, however, is that [classes don't inherit serialization by default](https://github.com/weichx/cerialize#inheriting-serialization). Since Iridium creates a virtual subclass to optimize the way properties are accessed this may mean that your serialization info is lost along the way...

The approach I've always taken in developing these systems is that the API is the defining aspect of them, so my backend models are in the same format as those presented by the API and I use a combination of validators and `pick` to ensure we don't ingest anything malformed or extraneous (everything else is covered by the validators). I suppose, if I really wanted to make things DRY there, I would probably derive my `pick` statement from the model's Schema like this:

```typescript
import {pick} from "lodash";

const data = {
  "_id": "abcd",
  "email": "ab@c.d"
}

db.Model.create(pick(data, Object.keys(db.Model.schema))).then(inserted => {
  console.log(inserted);
})
```

In using the `schema`, you're effectively automatically managing your `pick` statements as your model evolves. From that point onwards, any specific limitations (you can't change the email unless you're an admin, for example) become a business logic aspect and you can just tack them on like this:

```typescript
omit(pick(data, Object.keys(db.Model.schema)), "email")
```

**Comment by ChrLipp** [comment]
Thanks a lot for this answer! I resolved it with the following code:

        const dataToUpdate = DeserializeInto(request.body,
            XxxDocument, {} as IXxxSpaceDocument);
        this.model.update({ _id: _id }, { $set: dataToUpdate })

So I deserialized into an empty object and applied the annotations for the deserialization at the document. The caveat is that I have to specify the serialization rules on the document and therefor I am not able to specify it per request (update may be different to insert).

**Comment by SPARTAN563** [comment]
Hmm, the per-request stuff I'd argue belongs as part of the request handler's logic anyway, depending on where you're implementing the restrictions in your object tree, you may be able to get around it using just a `delete dateToUpdate["property"]` (or use `omit, since it does allow property paths`).

**Comment by SPARTAN563** [comment]
Glad to hear you managed to come right with it though, feel free to ask if you run into anything else.
