### ISSUE TITLE
Insert documents with upsert option doesn't create _id?

### ISSUE THREAD

**Issue by pyros2097** [SierraSoftworks/Iridium#66]
I tried to insert multiple documents and also had the { upsert: true } flag and all the docs were beignt created with { _id: null } value and when upsert is false is works properly.

**Comment by SPARTAN563** [comment]
Are you explicitly passing `{ _id: null }` into your requests? If so, I believe it'll pass `null` as a value through to MongoDB and that's what you're seeing (`null` is a valid value in JavaScript). I suspect you'll have better luck using `{ _id: undefined }` or, better yet, not specifying `_id` at all.

I'll also quickly extend the test suite to double check this use case, however it is one that I've used so I'm 95% sure it should be working correctly. I'll let you know as soon as that's done and if I find any issues.

**Comment by SPARTAN563** [comment]
Just put together the tests and you're entirely correct - `Model.insert()` and `Model.create()` both don't handle a missing `_id` well for the `upsert: true` case. To be perfectly honest, I'm not sure how you'd use it without an `_id` specified (as it does a replacement of the document based on `_id`), but I've updated it so that if the `_id` is missing it'll always create the document.

The correct way to do upserts is probably to use `Model.update()`, which will allow you to specify the match conditions and any update operations (including `$setOnInsert` etc) you wish.

```typescript
myModel.update({ email: "testy@mctester.son" }, { $inc: { awesomeness: 1 } })
```

I'll roll the fixes and let you know as soon as I've made a release with them. In the mean time, feel free to ask if you've got any other questions.

**Comment by pyros2097** [comment]
Thanks for the Quick Reply. Basically I was doing an insert with multiple documents and some documents had _id on them and some didn't and I would see the results have a strange document with _id: null and no new documents were being created.  As I expected those without _id to be new documents created with new _id but they were all routed to _id: null document.

**Comment by SPARTAN563** [comment]
I've just pushed the changes for v7.1.1, builds should be running now and I'll publish the package once they're done (and have passed on Travis).

Just so you're aware, by setting `{ upsert: true }` you're adding a big performance penalty in your code (it can't use `insertMany` anymore and needs to run multiple queries). I can probably try and hide that away so you only pay it on documents which have `_id` present (potentially reducing the impact) however that goes against one of the driving design decisions in Iridium - which is that everything should be consistently fast/slow to enable you to develop around it; rather than it sometimes being fast and sometimes slow.

My recommendation there would be to pre-filter your list of documents based on presence of `_id` and fire the ones without `_id`s at `insert()` with `{ upsert: false }` to take advantage of parallel inserts there, using `{ upsert: true }` on the remainder.

**Comment by SPARTAN563** [comment]
Version 7.1.2 of the package was just published with a fix for that behavior in it. Let me know if you run into any other issues :+1:.

**Comment by pyros2097** [comment]
Well then how do you do updates? I tried to do an update on a document like this,
`db.Apps.update({ serialNumber:  slNo }, { $set: { totalAmount: 2000 }})`

But then I get this error,
```
 Types of property '$set' are incompatible.
    Type '{ type:  totalAmount: number; }' is not assignable to type 'BSONObject'.
```
It seesms the $set only applies to BSON and not an object type. How do I convert my object to a BSONObject?

**Comment by SPARTAN563** [comment]
I'm trying to figure out why that would be breaking for you. The `BSONObject` type is just an alias for "something which can be serialized to BSON" (so basically any JSON document structure). Even testing the code you provided in my local environment seems happy.

Just to confirm, I've got this in my local environment...

```typescript
interface Doc {
  _id?: string;
  serialNumber: number;
  totalAmount: number;
}

class Instance extends Iridium.Instance<Doc, Instance> {
  @Iridium.ObjectID
  _id: string;

  @Iridium.Property(Number)
  serialNumber: number;

  @Iridium.Property(Number)
  totalAmount: number;
}

class Core extends Iridium.Core {
  Test = new Iridium.Model<Doc, Instance>(this, Instance);
}

const core = new Core("mongodb://localhost:27017");
core.Test.create({ serialNumber: 1, totalAmount: 0 }).then(() => {
  return core.Test.update({ serialNumber: 1 }, { $set: { totalAmount: 2000 } })
})
```

**Comment by pyros2097** [comment]
Yeah.. It seems its working but there is some weird typescript error with arrays. Don't got it fixed by manually doing an map from the request and setting the items. Seems to work now but then lot more boilerplate code. Thanks.

**Comment by SPARTAN563** [comment]
I'm sorry to hear that, is there any chance you can modify the example I provided you until it breaks in the way you're seeing and send that back to me? I'd be more than happy to try and fix whatever the underlying issue is so we can get rid of that boilerplate for you...

**Comment by pyros2097** [comment]
Tried that .. Tried to add an items array in the interface and then make an update worked fine. Don't know what the issue particularly is but the interfaces which I have is pretty large and have a lot of transformation from the request to the response and a lot of type checked enums and things like that. I guess updating typescript might fix it. Thanks a lot. When I get time I'll try delving into the issue and see whats causing it and  it doesn't seem like any issue with iridium itself.

**Comment by SPARTAN563** [comment]
Damn, sorry to hear that's causing issues. I suspect it may well be complex things like enums and potentially circular references or complex types. The quick (and very dirty) solution is to just type-cast your change set to `<any>` for the time being - in practice it won't make much of a difference and is how Iridium behaved prior to v7.1.

If you do manage to find a reproducible case, I'll obviously do everything I can to make Iridium accommodate it. In the mean time, best of luck and hope you manage to come right.
