### ISSUE TITLE
Problem with tsconfig.json in VSCode

### ISSUE THREAD

**Issue by mamsoudi** [SierraSoftworks/Iridium#79]
Hey there,
Thanks for Iridium, I loved it, it's way faster and better than mongoose and other ODMs I've used before. 
Today I saw an error in VS Code console which I hadn't noticed before. I'm using Typescript `2.3.4` and VS Code `1.13` if it helps. So here's the Error:

``` 
file: 'file:///**/node_modules/iridium/tsconfig.json'
severity: 'Error'
message: 'No inputs were found in config file '/**/node_modules/iridium/tsconfig.json'. Specified 'include' paths were '["**/*"]' and 'exclude' paths were '["dist","node_modules"]'.'
at: '1,1'
source: 'ts'
```

It's not something I can't work with but I thought it definitely worths mentioning.

**Comment by SPARTAN563** [comment]
Hi @mamsoudi, I'm glad to hear you're enjoying using Iridium. Thanks for reporting that error, I'll quickly see if I can reproduce it locally and, if so, I'll issue a fix once I've figured out the cause.

We'd obviously prefer that these things don't happen and that the experience is seamless, but it's incredibly helpful when people report the issues so we can fix them as quickly as possible for everyone else.

**Comment by SPARTAN563** [comment]
Hi @mamsoudi, I've just tried to reproduce your error using the same version of Visual Studio and TypeScript with the latest build of Iridium (`v7.2.1`) with no luck. I used [this project](https://github.com/SierraSoftworks/Iridium-Example) to test it out.

If you've got the time, would you mind forking [that project](https://github.com/SierraSoftworks/Iridium-Example) and making any changes necessary to trigger the same behaviour so that I can investigate and suggest/implement a fix? Alternatively, if you've got anything you suspect may be the cause, feel free to post it here and I'll look into it (your project's `tsconfig.json` file might be a good starting point).

**Comment by mamsoudi** [comment]
Hi @SPARTAN563, 
Sure, I will But the error itself is indicated for iridium's tsconfig.json file inside `node_modules/iridum`.
Here's my config file: 
```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es6",
        "noImplicitAny": true,
        "moduleResolution": "node",
        "sourceMap": true,
        "outDir": "dist",
        "baseUrl": ".",
        "experimentalDecorators": true,
        "paths": {
            "*": [
                "node_modules/*",
                "src/types/*"
            ]
        }
    },
    "include": [
        "src/**/*"
    ]
}
```

As you can see, I'm including all ts files inside my src folder for ts compiler to compile and put inside dist folder. I don't get why it should complain about what you're excluding inside your tsconfig.json file!
