### ISSUE TITLE
TypeError: Class constructor Core cannot be invoked without 'new'

### ISSUE THREAD

**Issue by mas-dude** [SierraSoftworks/Iridium#99]
Just wondering if anyone else is getting the following error: 

TypeError: Class constructor Core cannot be invoked without 'new'

I am running Node 6.11.1  and have applied the harmony flag to nodemon by adding the following to my package.json file.
"nodemonConfig": {
    "execMap": {
      "js": "node --harmony"
    }
  }

Is there anything else I have to do?

**Comment by SPARTAN563** [comment]
Hi @mas-dude, I suspect this is because you're using the ES5 "class" format, which looks something like this (or are compiling your TypeScript to ES5):

```javascript
function MyCore() {
  Iridium.Core.apply(this, arguments); // Error location
}

require("util").inherits(MyCore, Iridium.Core);
```

As a result of calling `Iridium.Core` using `apply`, you end up bypassing the ES6 class requirement that you use `new`.

Instead, your class should be written like this:

```javascript
class MyCore extends Iridium.Core {

}
```

This will ensure that the constructor is called correctly (behind the scenes) and avoid the issue you're running into.

Please let me know if you run into any problems with this, or it doesn't solve the issue you're seeing.

**Comment by mas-dude** [comment]
Thanks for the quick response :). Changing the target property in my tsconfig.json file to es6 solved the problem. I am still new to node.
Do I still need the harmony flag? Seems to work without it.

**Comment by SPARTAN563** [comment]
Glad to hear that solved it for you, I don't think you need the `--harmony` flag unless you're using experimental features. It's always a good idea to look at the [features supported by your specific version of Node.js](https://nodejs.org/en/docs/es6/), but as a rule of thumb, you want to avoid using `--harmony` for production workloads since those features are not considered stable by the V8 team yet.

**Comment by mas-dude** [comment]
Thanks for the tip and help, much appreciated.
